### ISSUE TITLE
Eizo EV2750 support

### ISSUE THREAD

**Issue by pvxx** [elfmimi/hid-monitor-control#2]
First I want to thank you, I was looking for this for a long time (and spent hours trying all the linux-compatible eizo-stuff I found, without any luck) :smile:.

I just want to let you know, that this code works flawlessly on EV2750 (the model I have), only difference is it has just one DisplayPort (which works with DP1). I know very little python, the only thing I did was replace all "EV2760" strings with "EV2750" and changed 0x4059 to 0x4014 in device_id_pairs, so if you want, you can add it "nicely". I don't really know how "switch" arg is supposed to work, but giving output string works OK.

Thanks again and if you could add PbyP modes as well, it would be great :wink:.

**Comment by elfmimi** [comment]
Thank you for reporting. I have added EV2750 support in the latest commit. https://github.com/elfmimi/hid-monitor-control/commit/6d52bb1cdc767d4769a5a9e80e620e76eaacc8f1
Please check if it works.

For PbyP give two arguments. like : HDMI DVI
With 'switcher' you use buttons on your monitor's front edge to switch between inputs. I don't know if it works for EV2750.

**Comment by pvxx** [comment]
Sorry for late reply, it works OK, including PbyP; thanks again. Maybe add at least a short usage info when run without arguments :).

"switcher" works as well, "mode" button to DP, "volume" to HDMI and "brightness" to DVI, but it uses 100% of a CPU core while running; I don't plan using it, but if you need any help with debugging, just let me know.
